config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]

  resources :intro_requests
  resources :contacts
  resources :companies

  resources :connection_searches, only: [:new]
  get '/connection_searches/:q' => 'connection_searches#search'

  get '/connectors' => 'connectors#suggest'

  root 'intro_requests#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :contacts
  has_many :users, through: :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :user_contacts
  has_many :users, through: :user_contacts
  belongs_to :company
end

app/models/intro_request.rb
class IntroRequest < ActiveRecord::Base
  belongs_to :user

  paginates_per(10)

  scope :desc,  -> { order(id: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :intro_requests
  has_many :user_contacts
  has_many :contacts, through: :user_contacts
  has_many :companies, through: :contacts

  def add_contact(contact)
    contacts << contact unless contacts.include?(contact)
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user_contact.rb
class UserContact < ActiveRecord::Base
  belongs_to :user
  belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
end

app/controllers/connection_searches_controller.rb
class ConnectionSearchesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new

  end

  def search
    q = params[:q].downcase
    companies = Company.where('lower(name) LIKE ?', "#{q}%")
    contacts = Contact.where('lower(name) LIKE ?', "#{q}%")
    results = companies | contacts
    render json: unify(results)
  end

  private

  def unify(entities)
    entities.map do |e|
      {name: e.name, type: e.class.to_s}
    end
  end

end

app/controllers/connections_search_controller.rb
class ConnectionsSearchController < ApplicationController
  skip_before_action :verify_authenticity_token

  def search
    q = params[:q].downcase
    companies = Company.where('lower(name) LIKE ?', "#{q}%")
    contacts = Contact.where('lower(name) LIKE ?', "#{q}%")
    results = companies | contacts
    render json: unify(results)
  end

  private

  def unify(entities)
    entities.map do |e|
      {name: e.name, type: e.class.to_s}
    end
  end

end

app/controllers/connectors_controller.rb
class ConnectorsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def suggest
    name = params[:name]
    type = params[:type]
    klass = type.constantize
    instance = klass.find_by_name params[:name]
    render json: instance.users
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
end

app/controllers/intro_requests_controller.rb
class IntroRequestsController < ApplicationController
  before_action :authenticate_user!

  def index
    @intro_requests = IntroRequest.desc.page(page)
  end

  def create
    @intro_request = IntroRequest.create intro_request_params
    redirect_to intro_requests_path
  end

  private

  def page
    params[:page] || 0
  end

  def intro_request_params
    params.require(:intro_request).permit(:description, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.includes(:contacts).find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/intro_requests_helper.rb
module IntroRequestsHelper
end

app/views/application/_flashes.html.slim
-if flash[:notice] or flash[:alert]
  .flash-notices
    - if flash[:notice]
      .flash-notice = flash[:notice]
    - if flash[:alert]
      .flash-alert = flash[:alert]

app/views/application/_sidebar_nav_links.html.slim
li.sidenav__item
  = link_to "Intro Requests", intro_requests_path, class: 'sidenav__link'
li.sidenav__item
  = link_to "Find A Connection", new_connection_search_path, class: 'sidenav__link'
li.sidenav__item
  = link_to "Log Out", destroy_user_session_path, method: :delete, class: 'sidenav__link'

app/views/connection_searches/new.html.slim
h1 Find a connection

=react_component('ConnectionSearch')

h3 Can't find what you need?
= link_to "Create an Intro Request", new_intro_request_path

app/views/contacts/_contact.html.slim
.contact
  tr
    td
      = contact.name
    td
      = contact.title
    td
      = contact.company.name

app/views/intro_requests/_intro_request.html.slim
.intro-request-small
  .intro-request-small__username
    = link_to intro_request.user.full_name, user_path(intro_request.user)
  .intro-request-small__description
    = intro_request.description
  .intro-request-small__timestamp
    = time_ago_in_words(intro_request.created_at) + " ago"
hr

app/views/intro_requests/index.html.slim
h1 Intro Requests
.intro-requests
  = render @intro_requests

= paginate @intro_requests

app/views/intro_requests/new.html.slim
h1 New Intro Request
=form_for IntroRequest.new do |f|
  .form-group
    =f.label :description
    =f.text_area :description, class: 'form-control'
  =f.hidden_field :user_id, value: current_user.id
  =f.submit

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Intros
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    body
      #wrapper
        #sidebar-wrapper
          .sidebar-brand
            | Intros
          ul.sidebar-nav
            = render partial: 'sidebar_nav_links'
        #page-content-wrapper
          = render partial: 'flashes'
          .container
            .row
              .main
                = yield

app/views/users/show.html.slim
h1 = @user.full_name
h2 = mail_to @user.email

h2 Contacts

table.table
  th Name
  th Title
  th Company
  = render @user.contacts